### ISSUE TITLE
Switch expression causes compilation failures for JDK 13

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr_tests#3]
The following test files which are also used for JDK 13 are causing issues due to the switch expression JEP 325 being superseded by JEP 354 which uses `yield` instead of `break` to return results:
- `src_12/org/benf/cfr/tests/SwitchTest28.java`
- `src_12/org/benf/cfr/tests/SwitchTest29.java`
- `src_12/org/benf/cfr/tests/SwitchTest30.java`

**Comment by leibnitz27** [comment]
Yeah - I've recently updated CFR to emit yield but haven't pushed my test changes yet.  Will do soon

**Comment by leibnitz27** [comment]
(fwiw I don't think it's worth retaining the break syntax for certain varieties of the jdk....... Could be persuaded otherwise)
