### ISSUE TITLE
Add more operator precedence tests

### ISSUE THREAD

**Issue by Marcono1234** [leibnitz27/cfr_tests#6]
It appears the <code>PrecedenceTest<i>X</i></code> classes tests some operations where brackets have to be used to revert the evaluation order of operators due to precedence rules. However, it looks like not all operators are covered.

What do you think about adding a separate test class which checks [all operators](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html):
- One method which combines them all, e.g.:
    ```java
    int test(int i1, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, boolean b1, boolean b2, boolean b3, boolean b4, boolean b5, boolean b6, boolean b7) {
        return
            ~((((((Boolean) (((((((((b1 ? (i1 += i2 -= i3 *= i4 /= i5 %= i6 &= i7 ^= i8 |= i9 <<= i10 >>= i11 >>>= i12) == 0
            : b2) || b3) && b4) | b5) ^ b6) & b7) == b1 ? 1 : 2) < 2) == b2)) instanceof Object ? 1 : 2) << 2) + 1) * 2);
            
    }
    ```
- Methods for checking against the operator with next higher precedence, e.g. `&&` and `|`; `|` and `^`; ...

This would then also make it easier to see that all operators are covered instead of having to look in separate classes.
Please let me know if I should create a pull request.

**Comment by leibnitz27** [comment]
Oh dear god that's psychopathic.

Please feel free to do a pull request. (in general, if you have fun tests, feel free to do so).
