### ISSUE TITLE
Where to Install jdk1.6 from?

### ISSUE THREAD

**Issue by TeamworkGuy2** [leibnitz27/cfr_tests#9]
I've looked, oracle doesn't offer a download nor openjdk. Any suggestions where I can get the offical jdk1.6 for running these tests?
(I'm kicking myself for not keeping a copy from 10 yrs ago, but who knew back then that old versions of software would be important and would eventually be taken down by the companies that make them!)

**Comment by leibnitz27** [comment]
Did you try here? https://www.oracle.com/uk/java/technologies/oracle-java-archive-downloads.html

It has jdks going back to 1.1 ;)

**Comment by leibnitz27** [comment]
(in case you're wondering where 1.6 is on that page, java 6 == java 1.6)

**Comment by TeamworkGuy2** [comment]
Yes, I did find that page! But it requires me to create an account with a bit of personal info. I was hoping to avoid creating that, but if that's the only way...
Thanks for confirming directing me. cfr is amazing by the way!
I'm hoping to create a test for an enum docompilation problem I ran into. If I manage to create a simple test to reproduce the issue and find a fix in the cfr code, do you prefer that I submit the new (failing) test here first or a patch on the main cfr project first?
![image](https://user-images.githubusercontent.com/890595/127796409-ac6baec6-0c76-4433-a327-42e4e8992eb8.png)

**Comment by leibnitz27** [comment]
At the risk of being cheeky, I think you can maybe get away without being ... 100% ... honest in the form above ;)

It's fine to submit the failing test in the main CFR repo, though I appreciate the effort to have a go here first!

**Comment by TeamworkGuy2** [comment]
Haha, yes, I thought of the same solution, I've got jdk1.6 now. It was a pain to get everything compiled and running; I'll document some of my head pounding in `developer_docs\building.md` if you like and I'll send a pull request.
